# This script will do the autopackaging and upload and scan in the Veracode portal

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
    - task: Bash@3
      displayName: tf Scanner
      inputs:
          targetType: inline
          script: |
              pwd
              export VERACODE_API_KEY_ID=$(VERACODE_API_KEY_ID)
              export VERACODE_API_KEY_SECRET=$(VERACODE_API_KEY_SECRET)
              curl -fsS https://tools.veracode.com/veracode-cli/install | sh
              ./veracode scan --type directory --source '$(Build.SourcesDirectory)' --format table 2 >&1 | tee container-scan-tf.json